"""create_flight_table

Revision ID: eb577eb6b73c
Revises: ff41ebb9e8a9
Create Date: 2026-09-02 11:44:38.960044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb577eb6b73c'
down_revision: Union[str, None] = 'ff41ebb9e8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('origin_airport_id', sa.Uuid(), nullable=False),
    sa.Column('destination_airport_id', sa.Uuid(), nullable=False),
    sa.Column('departure_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('arrival_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DEPARTED', 'ARRIVED', 'CANCELLED', name='flightstatus'), nullable=False),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###
